import type { VoiceAgent } from "@/features/agent-library/types";

export const voiceAgents: VoiceAgent[] = [
  {
    id: "voice-001",
    name: "Sarah Chen",
    description: "Warm, professional tone ideal for property consultations and client onboarding calls.",
    tags: [
      { label: "Professional", category: "tone" },
      { label: "English (US)", category: "accent" },
      { label: "Female", category: "gender" },
      { label: "Sales", category: "use-case" },
    ],
    accent: "purple",
    sampleDurationSeconds: 18,
    assigned: true,
    recommendedFor: "Inbound property inquiries",
  },
  {
    id: "voice-002",
    name: "James Mitchell",
    description: "Confident and clear delivery suited for outbound lead reactivation campaigns.",
    tags: [
      { label: "Confident", category: "tone" },
      { label: "English (UK)", category: "accent" },
      { label: "Male", category: "gender" },
      { label: "Outbound", category: "use-case" },
    ],
    accent: "blue",
    sampleDurationSeconds: 22,
    assigned: false,
    recommendedFor: "Lead reactivation",
  },
  {
    id: "voice-003",
    name: "Priya Sharma",
    description: "Friendly conversational style perfect for follow-ups and appointment scheduling.",
    tags: [
      { label: "Friendly", category: "tone" },
      { label: "English (IN)", category: "accent" },
      { label: "Female", category: "gender" },
      { label: "Support", category: "use-case" },
    ],
    accent: "green",
    sampleDurationSeconds: 16,
    assigned: false,
    recommendedFor: "Appointment booking",
  },
  {
    id: "voice-004",
    name: "Marcus Lee",
    description: "Authoritative voice for premium listings and high-value client conversations.",
    tags: [
      { label: "Authoritative", category: "tone" },
      { label: "English (SG)", category: "accent" },
      { label: "Male", category: "gender" },
      { label: "Premium", category: "use-case" },
    ],
    accent: "gold",
    sampleDurationSeconds: 20,
    assigned: true,
    recommendedFor: "Luxury property sales",
  },
  {
    id: "voice-005",
    name: "Emma Watson",
    description: "Calm and empathetic tone for sensitive client situations and complaint handling.",
    tags: [
      { label: "Empathetic", category: "tone" },
      { label: "English (AU)", category: "accent" },
      { label: "Female", category: "gender" },
      { label: "Support", category: "use-case" },
    ],
    accent: "pink",
    sampleDurationSeconds: 19,
    assigned: false,
    recommendedFor: "Customer support",
  },
  {
    id: "voice-006",
    name: "David Okonkwo",
    description: "Energetic and persuasive voice built for outbound campaign conversions.",
    tags: [
      { label: "Energetic", category: "tone" },
      { label: "English (US)", category: "accent" },
      { label: "Male", category: "gender" },
      { label: "Outbound", category: "use-case" },
    ],
    accent: "purple",
    sampleDurationSeconds: 15,
    assigned: false,
    recommendedFor: "Cold outreach",
  },
  {
    id: "voice-007",
    name: "Yuki Tanaka",
    description: "Soft and approachable delivery for first-time buyer guidance and education.",
    tags: [
      { label: "Soft", category: "tone" },
      { label: "English (US)", category: "accent" },
      { label: "Female", category: "gender" },
      { label: "Education", category: "use-case" },
    ],
    accent: "blue",
    sampleDurationSeconds: 17,
    assigned: false,
    recommendedFor: "First-time buyers",
  },
  {
    id: "voice-008",
    name: "Alex Rivera",
    description: "Neutral corporate tone for multi-tenant and B2B reseller communications.",
    tags: [
      { label: "Corporate", category: "tone" },
      { label: "English (US)", category: "accent" },
      { label: "Neutral", category: "gender" },
      { label: "Enterprise", category: "use-case" },
    ],
    accent: "green",
    sampleDurationSeconds: 21,
    assigned: true,
    recommendedFor: "Enterprise accounts",
  },
  {
    id: "voice-009",
    name: "Sophie Laurent",
    description: "Elegant and refined voice for high-end marketing and brand campaigns.",
    tags: [
      { label: "Elegant", category: "tone" },
      { label: "English (UK)", category: "accent" },
      { label: "Female", category: "gender" },
      { label: "Marketing", category: "use-case" },
    ],
    accent: "gold",
    sampleDurationSeconds: 18,
    assigned: false,
    recommendedFor: "Brand campaigns",
  },
  {
    id: "voice-010",
    name: "Ryan Cooper",
    description: "Direct and efficient style for high-volume outbound calling operations.",
    tags: [
      { label: "Direct", category: "tone" },
      { label: "English (US)", category: "accent" },
      { label: "Male", category: "gender" },
      { label: "Outbound", category: "use-case" },
    ],
    accent: "pink",
    sampleDurationSeconds: 14,
    assigned: false,
    recommendedFor: "High-volume dialing",
  },
];
