import type { CallerIdRecord } from "@/features/caller-id/types";

export const callerIdRecords: CallerIdRecord[] = [
  {
    id: "cid-001",
    label: "PropNex Main Line",
    phoneNumber: "+65 6789 0101",
    region: "Singapore",
    type: "both",
    verification: "verified",
    isDefault: true,
    assignedTo: "All campaigns",
    addedAt: "2026-06-12T08:00:00Z",
  },
  {
    id: "cid-002",
    label: "Outbound Sales",
    phoneNumber: "+65 6789 0102",
    region: "Singapore",
    type: "outbound",
    verification: "verified",
    isDefault: false,
    assignedTo: "Lead Reactivation",
    addedAt: "2026-06-18T10:30:00Z",
  },
  {
    id: "cid-003",
    label: "Support Hotline",
    phoneNumber: "+65 6789 0103",
    region: "Singapore",
    type: "inbound",
    verification: "verified",
    isDefault: false,
    assignedTo: "Inbound agent",
    addedAt: "2026-07-02T14:15:00Z",
  },
  {
    id: "cid-004",
    label: "KL Regional Office",
    phoneNumber: "+60 3 1234 5678",
    region: "Malaysia",
    type: "outbound",
    verification: "pending",
    isDefault: false,
    assignedTo: "Malaysia outreach",
    addedAt: "2026-07-20T09:00:00Z",
  },
  {
    id: "cid-005",
    label: "Premium Listings",
    phoneNumber: "+65 6789 0105",
    region: "Singapore",
    type: "outbound",
    verification: "verified",
    isDefault: false,
    assignedTo: "Luxury property sales",
    addedAt: "2026-07-28T11:45:00Z",
  },
  {
    id: "cid-006",
    label: "Jakarta Branch",
    phoneNumber: "+62 21 5555 1234",
    region: "Indonesia",
    type: "both",
    verification: "failed",
    isDefault: false,
    addedAt: "2026-08-01T16:20:00Z",
  },
];

export const regionOptions = [
  "Singapore",
  "Malaysia",
  "Indonesia",
  "India",
  "United Kingdom",
  "United States",
];
